### ISSUE TITLE
Command optimization

### ISSUE THREAD

**Issue by scc172fly** [PureMVC/puremvc-csharp-multicore-framework#4]
I've been using PureMVC for a long time, and the latest version also optimizes reflection, but commands can also be optimized. Commands should be managed by an object pool. Although commands are stateless, frequent use of commands results in frequent creation and destruction, which affects operation efficiency. At this time, we need an object pool for optimization, There is no need for frequent creation and destruction operations. Looking forward to your further optimization.

**Comment by saadshams** [comment]
For Commands besides being stateless, and should go away after execution, I'd like to add lightweight to the equation. 

Commands creation and destruction should be lightweight and anything that can cause the inefficiency  is possibly because of creation/destruction of expensive objects there.

If that's the case then such operations should be handled in proxies which themselves are long lived cached objects and can also handle the object pool. This housekeeping should live in the model and the proxy while hiding it from the controller layer.

I'd also like to clear that the newer version doesn't use Reflection and instead uses [Factory Func Delegate](https://docs.microsoft.com/en-us/dotnet/api/system.func-2) supplied by the user of PureMVC and that is way more efficient when it comes to memory overhead and execution.  

````C#
RegisterCommand(STARTUP, () => new StartupCommand());
````

This framework while conforming to AS3 reference implementation is frozen as per the [puremvc.org](http://puremvc.org), except for any language/syntax updates or bug fixes. Any additional features will happen through extensions or plugins ([Open/Closed Principle](https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle)).

Also if you can elaborate on what or how is it causing the inefficiencies in your operations, we can help you there for the right approach.

**Comment by cliffhall** [comment]
Commands definitely should not be instantiated prior to use, nor be reused. Otherwise the intended stateless nature may not be observed, or cumbersome cleanup logic could have to be implemented. If you’re  are intentionally mindful of this, it’s possible you could achieve some efficiency, but as Saad mentioned above you can implement this in a Proxy if you have a situation where instantiating a command is onerously compute intensive. In most cases it is not, so the framework itself doesn’t include a Command object pool.
